import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import { mockCustomers, mockTransactions, mockDocuments, mockAgents } from "./src/mockDb";
import { AgentId, WorkflowStep, DecisionReport, AgentState } from "./src/types";

const app = express();
const PORT = 3000;

app.use(express.json());

// Initialize Gemini API client
let ai: GoogleGenAI | null = null;
const apiKey = process.env.GEMINI_API_KEY;

if (apiKey && apiKey !== "MY_GEMINI_API_KEY" && apiKey.trim() !== "") {
  try {
    ai = new GoogleGenAI({
      apiKey: apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
    console.log("BankOS AI: Gemini API client initialized successfully.");
  } catch (error) {
    console.error("BankOS AI: Failed to initialize Gemini Client:", error);
  }
} else {
  console.log("BankOS AI: No active GEMINI_API_KEY found. Running in high-fidelity simulation mode.");
}

// REST API Endpoints
app.get("/api/customers", (req, res) => {
  res.json(mockCustomers);
});

app.get("/api/transactions", (req, res) => {
  const { customerId } = req.query;
  if (customerId) {
    res.json(mockTransactions.filter((tx) => tx.customerId === customerId));
  } else {
    res.json(mockTransactions);
  }
});

app.get("/api/documents", (req, res) => {
  const { customerId } = req.query;
  if (customerId) {
    res.json(mockDocuments.filter((doc) => doc.customerId === customerId));
  } else {
    res.json(mockDocuments);
  }
});

app.get("/api/agents", (req, res) => {
  res.json(mockAgents);
});

let apiCooldownUntil = 0;

// A helper function to call Gemini safely, with fallback to highly intelligent rule-based templates if API Client is unavailable
async function queryAgent(agentId: AgentId, systemPrompt: string, userPrompt: string): Promise<{ text: string; simulated?: boolean }> {
  if (ai) {
    if (Date.now() < apiCooldownUntil) {
      console.log(`BankOS AI: API is in cooldown mode. Directing agent ${agentId} to high-fidelity simulated backup engine.`);
      return { text: getSimulatedAgentResponse(agentId, userPrompt), simulated: true };
    }
    try {
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: userPrompt,
        config: {
          systemInstruction: systemPrompt,
          temperature: 0.2,
        },
      });
      return { text: response.text || "No response text generated by AI.", simulated: false };
    } catch (error: any) {
      const errorMessage = error?.message || String(error);
      const isQuotaError = errorMessage.includes("429") || errorMessage.includes("quota") || errorMessage.includes("RESOURCE_EXHAUSTED");
      
      if (isQuotaError) {
        apiCooldownUntil = Date.now() + 45000; // 45 seconds cooldown
        console.warn(`BankOS AI [Quota Warning]: Quota exceeded (429) for agent ${agentId}. Commencing 45s simulation-only cooldown.`);
      } else {
        console.error(`Gemini call failed for agent ${agentId}:`, error);
      }
      // Fallback to local intelligence if rate-limited or transient failure
    }
  }

  // High-fidelity fallback logic simulating realistic AI agent outputs
  return { text: getSimulatedAgentResponse(agentId, userPrompt), simulated: true };
}

// Main AI chat endpoint
app.post("/api/chat", async (req, res) => {
  const { message, history, activeAgentId } = req.body;
  
  if (!message) {
    return res.status(400).json({ error: "Message is required." });
  }

  const selectedAgent = mockAgents.find((a) => a.id === activeAgentId) || mockAgents.find((a) => a.id === AgentId.ORCHESTRATOR)!;
  const systemPrompt = selectedAgent.systemPrompt + "\nFormat your output nicely with markdown. Speak directly and professionally as a senior bank intelligence expert.";

  // Build simple chat context from history
  const contextHistory = Array.isArray(history)
    ? history.slice(-6).map((h: any) => `${h.sender === "user" ? "User" : "Agent"}: ${h.text}`).join("\n")
    : "";
  
  const userPrompt = `${contextHistory}\nUser says: ${message}\nAgent response:`;

  try {
    const result = await queryAgent(selectedAgent.id, systemPrompt, userPrompt);
    res.json({
      text: result.text,
      agentId: selectedAgent.id,
      agentName: selectedAgent.name,
      simulated: !!result.simulated
    });
  } catch (err: any) {
    res.status(500).json({ error: err.message || "Internal server error" });
  }
});

// Advanced multi-agent orchestration workflow endpoint
app.post("/api/orchestrate", async (req, res) => {
  const { customerId, type, meta } = req.body;
  
  const customer = mockCustomers.find((c) => c.id === customerId);
  if (!customer) {
    return res.status(404).json({ error: "Customer not found." });
  }

  const transactions = mockTransactions.filter((t) => t.customerId === customerId);
  const documents = mockDocuments.filter((d) => d.customerId === customerId);

  console.log(`Starting BankOS Multi-Agent Workflow: ${type} request for customer ${customer.name}`);

  // Create individual agent context summaries
  const customerSummary = JSON.stringify({
    name: customer.name,
    creditScore: customer.creditScore,
    monthlyIncome: customer.monthlyIncome,
    existingDebt: customer.existingDebt,
    employmentStatus: customer.employmentStatus,
    kycStatus: customer.kycStatus,
    pepStatus: customer.pepStatus,
    address: customer.address
  }, null, 2);

  const txSummary = JSON.stringify(transactions.map(t => ({
    amount: t.amount,
    category: t.category,
    description: t.description,
    type: t.type,
    location: t.location,
    riskLevel: t.riskLevel,
    flagReason: t.flagReason,
    status: t.status
  })), null, 2);

  const docSummary = JSON.stringify(documents.map(d => ({
    type: d.type,
    fileName: d.fileName,
    status: d.status,
    ocrConfidence: d.ocrConfidence,
    issues: d.issues,
    extractedData: d.extractedData
  })), null, 2);

  const metaSummary = JSON.stringify(meta || {}, null, 2);

  // Define which agents participate in what workflows
  const participatingAgents: AgentId[] = [];
  if (type === "loan") {
    participatingAgents.push(AgentId.LOAN_OFFICER, AgentId.RISK_ANALYST, AgentId.DOCUMENT_INTELLIGENCE, AgentId.CUSTOMER_RELATIONSHIP);
  } else if (type === "compliance_audit") {
    participatingAgents.push(AgentId.COMPLIANCE, AgentId.DOCUMENT_INTELLIGENCE, AgentId.FRAUD_DETECTION);
  } else if (type === "fraud_investigation") {
    participatingAgents.push(AgentId.FRAUD_DETECTION, AgentId.RISK_ANALYST, AgentId.COMPLIANCE);
  } else {
    // default/onboarding
    participatingAgents.push(AgentId.COMPLIANCE, AgentId.DOCUMENT_INTELLIGENCE, AgentId.CUSTOMER_RELATIONSHIP);
  }

  const agentReports: Record<string, any> = {};
  const steps: WorkflowStep[] = [];

  // Run the agent queries (can be executed in parallel for performance)
  const agentPromises = participatingAgents.map(async (agentId) => {
    const agent = mockAgents.find(a => a.id === agentId)!;
    
    let promptText = `
      Perform analysis for the following Customer Request:
      - WORKFLOW TYPE: ${type.toUpperCase()}
      - REQUEST METADATA: ${metaSummary}

      CUSTOMER PORTFOLIO DATA:
      ${customerSummary}

      CUSTOMER REAL-TIME TRANSACTIONS:
      ${txSummary}

      CUSTOMER UPLOADED REGULATORY DOCUMENTS:
      ${docSummary}

      Instructions for your report:
      1. Provide a final recommendation: Choose from [approve], [deny], [flag], [neutral]. Include the choice exactly in brackets.
      2. Set a confidence level score between 0 and 100.
      3. List 2 to 4 bulleted findings.
      4. Format your report clearly using Markdown.
    `;

    const result = await queryAgent(agentId, agent.systemPrompt, promptText);
    
    // Parse the recommendation and confidence score from the text
    const textLower = result.text.toLowerCase();
    let recommendation: "approve" | "deny" | "flag" | "neutral" = "neutral";
    if (textLower.includes("[approve]")) recommendation = "approve";
    else if (textLower.includes("[deny]")) recommendation = "deny";
    else if (textLower.includes("[flag]")) recommendation = "flag";

    // Extract confidence (or default to 85)
    const confidenceMatch = result.text.match(/confidence.*(\d{2})/i) || result.text.match(/score.*(\d{2})/i);
    const confidence = confidenceMatch ? parseInt(confidenceMatch[1], 10) : 85;

    // Extract bullet points as findings
    const findings: string[] = [];
    const lines = result.text.split("\n");
    for (const line of lines) {
      if (line.trim().startsWith("-") || line.trim().startsWith("*")) {
        findings.push(line.replace(/^[-*\s]+/, "").trim());
      }
    }
    if (findings.length === 0) {
      findings.push(`Completed analysis on ${type} request.`);
      findings.push(`Identified key status as ${recommendation.toUpperCase()}.`);
    }

    agentReports[agentId] = {
      recommendation,
      confidence,
      findings: findings.slice(0, 4),
      details: result.text
    };

    steps.push({
      id: `step-${agentId}-${Date.now()}`,
      agentId,
      agentName: agent.name,
      timestamp: new Date().toLocaleTimeString(),
      action: `Completed ${type} assessment`,
      recommendation,
      details: findings[0] || "Completed analysis report."
    });
  });

  await Promise.all(agentPromises);

  // Now feed all agent reports to the ORCHESTRATOR agent to synthesize the final explainable decision!
  const orchestratorAgent = mockAgents.find(a => a.id === AgentId.ORCHESTRATOR)!;
  const reportsPayload = JSON.stringify(agentReports, null, 2);

  const orchestratorPrompt = `
    You are the central BankOS Multi-Agent Orchestrator. You must synthesize the specialized agent assessments for the following customer request:
    - CUSTOMER: ${customer.name} (Credit Score: ${customer.creditScore}, Monthly Income: INR ${customer.monthlyIncome})
    - REQUEST TYPE: ${type.toUpperCase()}
    - DETAILS: ${metaSummary}

    SPECIALIZED AGENT ASSESSMENT REPORTS:
    ${reportsPayload}

    Your goals:
    1. Resolve conflicts. (e.g. if compliance flags KYC issues but lending says approve, determine the proper course of action).
    2. Provide a definitive system outcome status. Output one of: [APPROVED], [DENIED], [FLAGGED_FOR_REVIEW] exactly in brackets.
    3. Calculate an aggregate Risk Score (0-100) based on agent concerns.
    4. Provide a structured, highly explainable banking decision memo including:
       - EXECUTIVE CONCLUSION
       - RISK MITIGATION / RESOLUTION STEPS
       - REGULATORY & OPERATIONAL DISCLOSURES
  `;

  const orchResult = await queryAgent(AgentId.ORCHESTRATOR, orchestratorAgent.systemPrompt, orchestratorPrompt);

  let status: "approved" | "denied" | "flagged_for_review" = "flagged_for_review";
  const orchTextLower = orchResult.text.toLowerCase();
  if (orchTextLower.includes("[approved]")) status = "approved";
  else if (orchTextLower.includes("[denied]")) status = "denied";
  else if (orchTextLower.includes("[flagged_for_review]")) status = "flagged_for_review";

  // Compute a blended Risk Score
  let calculatedRisk = customer.riskScore;
  const riskScores = Object.values(agentReports).map(r => r.recommendation === "deny" ? 30 : r.recommendation === "flag" ? 15 : 0);
  calculatedRisk = Math.min(95, Math.max(5, customer.riskScore + riskScores.reduce((a, b) => a + b, 0)));

  const finalReport: DecisionReport = {
    id: `decision-${Date.now()}`,
    customerId,
    customerName: customer.name,
    title: `${type.toUpperCase().replace("_", " ")} Audit Report`,
    type,
    date: new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }),
    status,
    riskScore: calculatedRisk,
    orchestratorConclusion: orchResult.text,
    agentOpinions: agentReports as any,
    steps: steps.sort((a, b) => a.agentName.localeCompare(b.agentName))
  };

  res.json(finalReport);
});

// Fallback high-fidelity smart answers for offline/simulated mode
function getSimulatedAgentResponse(agentId: AgentId, userPrompt: string): string {
  const promptLower = userPrompt.toLowerCase();
  
  if (agentId === AgentId.LOAN_OFFICER) {
    if (promptLower.includes("aarav")) {
      return `### Loan Eligibility Assessment [approve]
- **Confidence Score:** 95
- **Debt-To-Income (DTI) Ratio:** 10.3% (Very Low - Outstanding)
- **Credit Rating Alignment:** 780 score indicates extremely reliable credit history.

**Key Findings:**
- Verified primary salary slip matches incoming transaction values perfectly.
- Existing debt service obligations (INR 15,000) represent less than 11% of stable net monthly income (INR 145,000).
- Eligible for the premium Home Loan segment with a highly competitive interest rate of 8.15% p.a.
- Recommended EMI Options: INR 52,400 per month for a 15-year tenure.`;
    } else if (promptLower.includes("rohan")) {
      return `### Loan Eligibility Assessment [deny]
- **Confidence Score:** 98
- **Debt-To-Income (DTI) Ratio:** 157.1% (Insolvent - Critical Risk)
- **Credit Rating Alignment:** 480 credit score represents high historic delinquency.

**Key Findings:**
- Existing debt (INR 55,000) exceeds current monthly income (INR 35,000) significantly.
- Income is highly volatile, listed as Unemployed in core bank ledger databases.
- Recommendation is to reject any lending extension immediately.`;
    } else {
      return `### General Loan Officer Assessment [neutral]
- **Confidence Score:** 85
- **Debt-To-Income (DTI) Ratio:** Calibrated based on requested parameters.

**Key Findings:**
- Evaluated stable monthly salary ledger credits.
- Existing debt ratios analyzed against standard IDBI internal lending parameters.
- Recommended credit limits aligned to standard product portfolios.`;
    }
  }

  if (agentId === AgentId.FRAUD_DETECTION) {
    if (promptLower.includes("priya")) {
      return `### Fraud Sentinel Security Scan [flag]
- **Confidence Score:** 94
- **Security Alert Class:** Location anomaly and rapid card-velocity flag (Impossible Travel).

**Key Findings:**
- Detected high-value online international transaction (INR 49,999) from a US-registered IP address at 01:10 AM.
- Detected a secondary physical point-of-sale terminal debit (INR 35,000) in JP Nagar, Bengaluru just 5 minutes later at 01:15 AM.
- Distance-Velocity mismatch: Travel time from US IP to Bengaluru POS requires physically impossible supersonic transport speeds. Suggest high threat of card cloning.
- Action items: Account held. Auto-initiated high-risk card lock. SMS Verification dispatched.`;
    } else {
      return `### Fraud Sentinel Security Scan [approve]
- **Confidence Score:** 97
- **Security Alert Class:** Normal baseline operations.

**Key Findings:**
- No impossible travel metrics detected in the recent transaction sequence.
- All transactional velocities fall well within historical user parameters.
- Device signatures, IP geolocations, and merchant categories are verified low risk.`;
    }
  }

  if (agentId === AgentId.COMPLIANCE) {
    if (promptLower.includes("rohan")) {
      return `### Regulatory Compliance Checklist [flag]
- **Confidence Score:** 92
- **Regulatory Checklist Status:** PEP Warning and KYC Failures.

**Key Findings:**
- PEP Screening flagged high-match probability: Client has documented close family relationship with a politically exposed official in West Bengal.
- AML Screening Alert: Flagged suspicious rapid cash deposits structured just below mandatory FIU-IND reporting thresholds.
- KYC Status is currently marked as failed/unverified. Active address does not match documented regional PAN registration.
- Critical Action: File suspicious activity report (SAR) with Compliance Committee. Account must be suspended pending secondary proof of funds.`;
    } else {
      return `### Regulatory Compliance Checklist [approve]
- **Confidence Score:** 98
- **Regulatory Checklist Status:** Clear KYC and AML baseline.

**Key Findings:**
- Customer KYC status is fully validated against government primary records (PAN & Aadhaar linked successfully).
- Checked database index tables: PEP matching score is 0.0% (Clear).
- AML thresholds checked: No high-volume transfers or suspicious cash structuring patterns found.`;
    }
  }

  if (agentId === AgentId.DOCUMENT_INTELLIGENCE) {
    if (promptLower.includes("vikram")) {
      return `### OCR Document Trust Audit [flag]
- **Confidence Score:** 88
- **OCR Validation Index:** Flagged Mismatch / Low Scan Resolution.

**Key Findings:**
- PAN Card validation failed: Found critical typographical character replacement (the character 'O' was scanned as the digit '0' in PAN "LMN0P9012Q").
- Structural analysis: Photo clarity index falls at 48%, below the institutional quality assurance standard of 65%.
- Recommendation: Flag document as suspect/unverified. Trigger manual document re-upload interface for Vikram Singh.`;
    } else {
      return `### OCR Document Trust Audit [approve]
- **Confidence Score:** 99
- **OCR Validation Index:** Fully Verified.

**Key Findings:**
- Structural document parameters verify high-resolution, genuine print patterns.
- OCR text matching achieves 99.2% matching precision with Government registry data.
- Digital watermark signatures and QR code segments validated successfully.`;
    }
  }

  if (agentId === AgentId.CUSTOMER_RELATIONSHIP) {
    return `### Hyper-Personalized Wealth Engagement [approve]
- **Confidence Score:** 90
- **Customer Lifetime Value Segment:** High Asset Retention Recommendation.

**Key Findings:**
- Client holds substantial positive net balances. Highly eligible for high-yield deposit accounts.
- Identified cross-selling matches: Recommend IDBI Signature Credit Card with premium lounge benefits.
- Advisory trigger: Propose automated tax savings plans or tax-saving equity-linked schemes (ELSS).`;
  }

  if (agentId === AgentId.RISK_ANALYST) {
    if (promptLower.includes("rohan")) {
      return `### Credit Risk Assessment [deny]
- **Confidence Score:** 96
- **Stress-Testing Probability of Default:** 91.2% (Extremely High Risk).

**Key Findings:**
- Extremely poor debt consolidation status (DTI ratio exceeds 150%).
- Cash-to-Debt buffer is near-zero. No liquid savings cushion.
- Under institutional stress-testing, early default indicators are triggered across multiple models. Strict credit block recommended.`;
    } else {
      return `### Credit Risk Assessment [approve]
- **Confidence Score:** 92
- **Stress-Testing Probability of Default:** 1.5% (Very Safe credit profile).

**Key Findings:**
- Robust monthly cash flow surplus. Healthy balance reserves.
- Liquidity score is outstanding. Able to sustain unexpected income reductions.
- Probability of default is negligible. Approved under all macro stress scenarios.`;
    }
  }

  // Central Orchestrator Simulated Synthesis
  return `### BankOS Executive Consensus Report [APPROVED]
- **Blended Risk Index Score:** 15/100 (Safe)
- **Consensus Verdict:** APPROVED FOR IMMEDIATE ACTION

**Orchestrator Synthesis Summary:**
The autonomous workflow has integrated reports from Lending, Compliance, Risk, and Document Intelligence. 
Compliance validates the customer's KYC standing as 100% verified. Document Intelligence reports flawless scan matches for both Aadhaar and Income payslips. 
Lending calculates a conservative and stable Debt-To-Income (DTI) ratio of 10.3%, indicating high repayment headroom. 
The Risk Analyst model reports an extremely low Probability of Default under macro-stressed interest rate models.

**Mitigation and Resolution Steps:**
- Disburse requested funds into verified primary current account.
- Configure automated auto-debit sweeps aligned to the primary payroll schedule.
- Auto-generate premium wealth advisory invitations via Customer Relationship AI.`;
}

// Start Server Setup (served in development or static production)
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
    console.log("BankOS AI: Running in development mode with Vite middleware.");
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
    console.log("BankOS AI: Running in production mode serving static dist files.");
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`BankOS AI Server running on http://localhost:${PORT}`);
  });
}

if (process.env.NODE_ENV !== "production" || !process.env.VERCEL) {
  startServer();
}

export default app;
